<?php 
echo "<div class='row'>";
echo "<div class='col-sm-6 col-md-6 col-lg-4 ftco-animate'>";
	echo "<div class='product'>";
		echo "<a href='#' class='img-prod'><img class='img-fluid' src='images/bg2.png' alt='Colorlib Template'>";
			echo "<div class='overlay'></div>";
		echo "</a>";
		echo "<div class='text py-3 px-3'>";
			echo "<h3><a href='#'>Floral Jackquard Pullover</a></h3>";
			echo "<div class='d-flex'>";
				echo "<div class='pricing'>";
				   	echo "<p class='price'><span>$120.00</span></p>";
				    echo "</div>";
			echo "</div>";
		    echo "<p class='bottom-area d-flex px-3'>";
		    	echo "<a href='#' class='add-to-cart text-center py-2 mr-1'><span>Add to cart <i class='ion-ios-add ml-1'></i></span></a>";
		    	echo "<a href='#' class='buy-now text-center py-2'>Buy now<span><i class='ion-ios-cart ml-1'></i></span></a>";
			echo "</p>";
		echo "</div>";
	echo "</div>";
echo "</div>";
echo "</div>";
